version: 2.1
# Use a package of configuration called an orb.
orbs:

  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@3.1.1
# Define the jobs we want to run for this project
#executors:
 #   default:
  #    machine:
   #     image: ubuntu-2004:202201-02
    #simple:
     # docker:
      #  - image: python:3.8
jobs:
 # aws-cli-example:
    #executor: aws-cli/default
    #steps:
     # - checkout
     # - aws-cli/setup:
    #      profile-name: example
   #   - run: echo "Run your code here"
  create_infrastructure: 
    docker:
      - image: Amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
              aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
          
          #shell: powershell.exe
# Sequential workflow
workflows:
  # Name the workflow
    my_workflow:
      jobs:
      #  - aws-cli-example
        - create_infrastructure
