version: 2.1
# Use a package of configuration called an orb.
orbs:

  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@3.1.1
# Define the jobs we want to run for this project

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
              aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine:3.16
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["b6:43:15:a9:af:07:ab:76:05:69:f7:fd:e2:ba:d4:92"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible

      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt  main1.yml
          
workflows:
  # Name the workflow
    my_workflow:
      jobs:
        - create_infrastructure
        - configure_infrastructure